## Numpy >> arrays and basics
Introduction to arrays

In [1]:
import numpy as np
import time

### Creating array

In [2]:
arr_1D = np.array([1,2,3,4])
print(f"1D array: {arr_1D}")

arr_2D = np.array([[1,2,3],[4,5,6]])
print(f"2D array: {arr_2D}")

1D array: [1 2 3 4]
2D array: [[1 2 3]
 [4 5 6]]


#### List vs Numpy array

In [3]:
print("Multiplication with scaler...\n")

py_list = [1,2,3]
print(f'''Python list multiplication example:
      {py_list}*2 = {py_list*2}''')
print("")

#element vise multiplication
np_array = np.array([1,2,3])
print(f'''Numpy array multiplication example:
      {np_array}*2 = {np_array*2}''')


start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Multiplication with scaler...

Python list multiplication example:
      [1, 2, 3]*2 = [1, 2, 3, 1, 2, 3]

Numpy array multiplication example:
      [1 2 3]*2 = [2 4 6]

 List operation time:  0.08930325508117676

 Numpy operation time:  0.004029750823974609


#### Creating array from scratch

In [4]:
zeros = np.zeros((3,4))          # zeros array
print(f"Zeros array: \n{zeros}")

ones = np.ones((2,3))            # ones array
print(f"Ones array: \n{ones}")

full = np.full((2,2),7)          # full array
print(f"Full array: \n{full}")

random = np.random.random((2,3)) # random array
print(f"Random array: \n{random}")

sequence = np.arange(0,11,2)     # array with the help of range
print(f"Sequence array: \n{sequence}")

Zeros array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
[[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
[[7 7]
 [7 7]]
Random array: 
[[6.43387439e-02 6.91040875e-01 2.16491848e-01]
 [4.68049911e-01 6.17170458e-01 6.13997931e-04]]
Sequence array: 
[ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3])                            # 1D
print(f"\nVector:\n{vector}")

matrix = np.array(([                                    # 2D
    [1, 2, 3],
    [4, 5, 6]
]))
print(f"\nMatrix:\n{matrix}")

tensor = np.array([[[1,2],[3,4]],
                   [[5,6], [7,8]]])       # 3D
print(f"\nTensor:\n{tensor}")


Vector:
[1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]]

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Array:\n{arr}\n")
print(f"Shape: {arr.shape}")
print(f"Dimension: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Dtype: {arr.dtype}")

Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimension: 2
Size: 6
Dtype: int64


#### Methods on arrays

In [7]:
arr = np.arange(12)
print(f"Original array:\n{arr}\n")

reshaped_arr = arr.reshape((3,4))
print(f"Reshaped array:\n{reshaped_arr}\n")

# it returns copy
flattened_arr = reshaped_arr.flatten()
print(f"Flattened array:\n{flattened_arr}\n")

# it returns view, instead of copy
raveled = reshaped_arr.ravel()
print(f"Raveled array:\n{raveled}\n")

transpose_1 = reshaped_arr.transpose()
transpose_2 = reshaped_arr.T   # it is an attribute (@property method)
print(f"Transposed array:\n{transpose_1}\n{transpose_2}\n")


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

