## Numpy Basics

In [2]:
import numpy as np

In [3]:
#Creating our first numpy array

my_arr = np.array([10, 20, 30, 40, 50])
print(f"Array = {my_arr}")

Array = [10 20 30 40 50]


#### 1d Array & 2d Array

In [4]:
num = 2 #scalar value 
arr_1d = np.array([1, 2, 3, 4, 5])    # 1D array or vector
print(f"1D Array: {arr_1d}")
# np.array takes single list arguement
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array or matrix
print(f"2D Array:\n{arr_2d}")

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]


#### List vs Numpy Array

In [5]:
print("Multiplication with scaler...\n")

py_list = [1, 2, 3, 4, 5]
print(f"Python list multiplied by 2: {py_list*2}")  #This will repeat the list instead of element-wise multiplication 

np_arr = np.array(py_list)
print(f"Numpy array multiplied by 2: {np_arr*2}")  #This will perform element-wise multiplication

Multiplication with scaler...

Python list multiplied by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplied by 2: [ 2  4  6  8 10]


##### Time Efficiency

In [6]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2   #arange in np is similar to range in python
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.10067462921142578

 Numpy operation time:  0.009003639221191406


#### Array Creation Methods

In [ ]:
zero_arr = np.zeros((3,4))  # zero array of 3 rows and 4 columns
print(f"Zeros Array:\n{zero_arr}\n")

one_arr = np.ones((3,4)) # ones array of 3 rows and 4 columns
print(f"Ones Array:\n{one_arr}\n")

full_arr = np.full((3,4),5)  # (all the elements are same,here-->5)  is equal to one_arr*5
print(f"Full Array:\n{full_arr}\n")

sequence = np.arange(1,10,2) # parameters --> (start,stop,step), it only returns 1D array
print(f"Sequence Array (using np.arange method):\n{sequence}\n")

rand_arr = np.random.random((3,4)) #it gives float array of random elements in open range (0,1)
# np.random is a whole class but np.random.random is method
print(f"Random Array:\n{rand_arr}\n")

randint_arr = np.random.randint(1,6,(3,4)) # elements range --> [1,6) #array size --> 3X4 3 rows 4 columns
print(f"Randint Array:\n{randint_arr}\n")


Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full Array:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

Array using arange method
[1 3 5 7 9]

Random Array:
[[0.62461585 0.46247664 0.07645858 0.51625228]
 [0.61707521 0.5513163  0.18152641 0.57951295]
 [0.79317691 0.77172563 0.88905265 0.09305564]]

Randint Array:
[[4 4 3 2]
 [2 3 2 4]
 [5 2 3 1]]



### Vector, Marix and Tensor

In [35]:
vec = np.array([1,2,3,4,5]) # 1d arrays are called Vector
print(f"Vector: {vec}\n")

matrix = np.array([[1,2,3],[4,5,6]]) # 2d arrays are called Matrix
print(f"Matrix:\n{matrix}\n")

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[4,5,6],[7,8,9]],
                   [[5,7,8],[7,5,3]]]) # 3d or more dimension arrays are called Tensor
print(f"Tensor:\n{tensor}")


Vector: [1 2 3 4 5]

Matrix:
[[1 2 3]
 [4 5 6]]

Tensor:
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[5 7 8]
  [7 5 3]]]
