## Numpy >> Array operation

In [ ]:
import numpy as np

### Indexing and Slicing

#### 1D Array 

In [1]:
arr =  np.array([1,2,3,4,5,6,7,8,10])
print("Basic Slicing:", arr[2:7])
print("\nWith Step:", arr[1:8:2])
print("\nNegative indexing:", arr[-4])       #here we used single index therfore it will return single element not array

NameError: name 'np' is not defined

#### 2D Array

In [ ]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
# Note: Unlike Matrix, indexing or counting of rows and columns are also started form zero in arrays
print("Specific Element: ", arr_2d[1, 2]) # When separated by comma it means row, column >> This will return intersection point of first row and second column

print("Entire row: ", arr_2d[0])
print("Entire column: ", arr_2d[:, 1])


Specific Element:  6
Entire row:  [1 2 3]
Entire column:  [2 5 8]


### Sorting Method

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1],
                            [1, 4],
                            [2, 5]])
print("Sorted 2D array by Column: ", np.sort(arr_2d_unsorted, axis = 1)) # every coloumn
print("Sorted 2D array by Row: ", np.sort(arr_2d_unsorted, axis = 0))

Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by Column:  [[1 3]
 [1 4]
 [2 5]]
Sorted 2D array by Row:  [[1 1]
 [2 4]
 [3 5]]


### Filter

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers:", even_number)

Even numbers: [ 2  4  6  8 10]


#### Filter with mask

In [ ]:
mask = numbers > 5
print(mask)
print("Number greater than 5 :", numbers[mask])

[False False False False False  True  True  True  True  True]
Number greater than 5 : [ 6  7  8  9 10]


### Fancy indexing vs np.where

In [ ]:
indices = [0, 2, 4] #enter postions that you wants, separated by commas
print(numbers[indices])

where_result = np.where(numbers>5)
print("np where:", numbers[where_result])

[1 3 5]
np where: [ 6  7  8  9 10]


In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#first argument is condition, second arguement is return 
# value for this codition and third arguement is else codition
condition_array = np.where(numbers > 5,  True, False) 
print(condition_array)

# It is just like
arr_num = numbers > 5
print(arr_num)

list_num = []
for number in numbers:
    if number>5:
        list_num.append(True)
    else:
        list_num.append(False)
print(list_num)

[False False False False False  True  True  True  True  True]
[False False False False False  True  True  True  True  True]
[False, False, False, False, False, True, True, True, True, True]


### Adding and Removing data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


#### Array Compatiblity

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatiblity shape:", a.shape == b.shape == c.shape)

Compatiblity shape: False


In [ ]:
original = np.array([[1, 2],[3, 4]])
print("Original array:\n",original)


new_row = np.array([[5, 6]])
with_new_row = np.vstack((original,new_row))
print(f"With new row:\n{with_new_row}")


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new column:\n",with_new_col)

Original array:
 [[1 2]
 [3 4]]
With new row:
[[1 2]
 [3 4]
 [5 6]]
With new column:
 [[1 2 7]
 [3 4 8]]


#### Delete

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(f"1D array:",arr)
arr_after_deletion = np.delete(arr,2) # arguments is (array,index)
print("Array after deletion:",arr_after_deletion)

arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print(f"2D array:",arr_2d)
deletion_2d = np.delete(arr_2d, 1, axis = 1) # column wise
print(f"2D array after deleltion:",deletion_2d)
deletion_2d = np.delete(arr_2d, 1, axis = 0) # row wise
print(f"2D array after deleltion:",deletion_2d)


1D array: [1 2 3 4 5]
Array after deletion: [1 2 4 5]
2D array: [[1 2 3]
 [4 5 6]]
2D array after deleltion: [[1 3]
 [4 6]]
2D array after deleltion: [[1 2 3]]
